In [1]:
import numpy as np 
import pandas as pd 

train_dset_df = pd.read_csv("./datasets/train.csv")
test_dset_df = pd.read_csv("./datasets/test.csv")

/home/akb/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (28) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


## Initial thoughts

Hmm.... lots of columns. Will really have to do some exploration first.

In [2]:
train_dset_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 567730 entries, 0 to 567729
Data columns (total 83 columns):
 #   Column                                             Non-Null Count   Dtype  
---  ------                                             --------------   -----  
 0   MachineIdentifier                                  567730 non-null  object 
 1   ProductName                                        567730 non-null  object 
 2   EngineVersion                                      567730 non-null  object 
 3   AppVersion                                         567730 non-null  object 
 4   AvSigVersion                                       567730 non-null  object 
 5   IsBeta                                             567730 non-null  int64  
 6   RtpStateBitfield                                   565459 non-null  float64
 7   IsSxsPassiveMode                                   567730 non-null  int64  
 8   DefaultBrowsersIdentifier                          29401 non-null   float6

## Going through each column

### 0. MachineIdentifier

In [3]:
train_dset_df.MachineIdentifier

0         5a5b96867f209ed62e97ae184213602e
1         4b2f9204f975df10a6acd2764553caee
2         6bc9d2ef844b832032428452f23c18c5
3         590ae8c480b7b15d1988808c44e81c39
4         703139809b69307b6a5b967da3b3e536
                        ...               
567725    4e0d50750857455883a5043646aeeede
567726    59b4842208c15636b278b252a8e4bf55
567727    52c99853c174e6738f53655b07ceb5c0
567728    61efcf0fe10292e3428172515b7b3d07
567729    ced026bed13a146f7f486cb4479c0a73
Name: MachineIdentifier, Length: 567730, dtype: object

In [4]:
train_dset_df.MachineIdentifier.nunique()

567730

There are as many unique values as there are rows in the dset. Therefore, it is safe to assume that MachineIdentifier is just a uniqueID. Will probably have to remove before training.

In [5]:
train_dset_df.MachineIdentifier.isna().sum()

0

### 1. ProductName

In [6]:
train_dset_df.ProductName

0         win8defender
1         win8defender
2         win8defender
3         win8defender
4         win8defender
              ...     
567725    win8defender
567726    win8defender
567727    win8defender
567728    win8defender
567729    win8defender
Name: ProductName, Length: 567730, dtype: object

Categorical - nominal? 

In [7]:
train_dset_df.ProductName.unique()

array(['win8defender', 'mse', 'mseprerelease', 'windowsintune', 'fep'],
      dtype=object)

In [8]:
train_dset_df.ProductName.isna().sum()

0

### 2. EngineVersion

In [9]:
train_dset_df.EngineVersion

0         1.1.15200.1
1         1.1.15100.1
2         1.1.15200.1
3         1.1.15200.1
4         1.1.15100.1
             ...     
567725    1.1.15200.1
567726    1.1.15200.1
567727    1.1.15200.1
567728    1.1.15100.1
567729    1.1.15200.1
Name: EngineVersion, Length: 567730, dtype: object

In [10]:
train_dset_df.EngineVersion.nunique()

55

In [11]:
train_dset_df.EngineVersion.isna().sum()

0

Categorical --- nominal. It does not make sense to have any specific ordering -- there is no guarantee that later versions are "better" due to the possibility of bugs etc.

### 3. AppVersion

In [12]:
train_dset_df.AppVersion

0          4.18.1807.18075
1          4.18.1807.18075
2          4.18.1807.18075
3          4.18.1807.18075
4              4.9.10586.0
                ...       
567725     4.18.1807.18075
567726     4.18.1807.18075
567727     4.18.1807.18075
567728     4.18.1807.18075
567729    4.12.17007.18022
Name: AppVersion, Length: 567730, dtype: object

In [13]:
train_dset_df.AppVersion.nunique()

96

In [14]:
train_dset_df.AppVersion.isna().sum()

0

Again, categorical-nominal

### 4. AvSigVersion

In [15]:
train_dset_df.AvSigVersion

0         1.275.1209.0
1         1.273.1519.0
2          1.275.790.0
3          1.275.155.0
4          1.273.879.0
              ...     
567725      1.275.41.0
567726    1.275.1209.0
567727     1.275.260.0
567728    1.273.1124.0
567729     1.275.850.0
Name: AvSigVersion, Length: 567730, dtype: object

In [16]:
train_dset_df.AvSigVersion.nunique()

6829

In [17]:
train_dset_df.AvSigVersion.isna().sum()

0

This needs to be categorical-nominal, but will add WAY more columns. Probably need to chuck column.

### 5. IsBeta

In [18]:
train_dset_df.IsBeta

0         0
1         0
2         0
3         0
4         0
         ..
567725    0
567726    0
567727    0
567728    0
567729    0
Name: IsBeta, Length: 567730, dtype: int64

In [19]:
train_dset_df.IsBeta.nunique()

2

In [20]:
train_dset_df.IsBeta.isna().sum()

0

Categorical, and already encoded.

### 6. RtpStateBitField

In [21]:
train_dset_df.RtpStateBitfield

0         7.0
1         7.0
2         7.0
3         7.0
4         7.0
         ... 
567725    7.0
567726    7.0
567727    7.0
567728    7.0
567729    7.0
Name: RtpStateBitfield, Length: 567730, dtype: float64

In [22]:
train_dset_df.RtpStateBitfield.unique()

array([ 7.,  0.,  5., nan,  8.,  3.,  1.])

Seems to be categorical - nominal. Further, there are missing values which must be imputed.

### 7 IsSxsPassiveMode

In [23]:
train_dset_df.IsSxsPassiveMode

0         0
1         0
2         0
3         0
4         0
         ..
567725    0
567726    0
567727    0
567728    0
567729    0
Name: IsSxsPassiveMode, Length: 567730, dtype: int64

In [24]:
train_dset_df.IsSxsPassiveMode.unique()

array([0, 1])

In [25]:
train_dset_df.IsSxsPassiveMode.isnull().sum()

0

Categorical, and already encoded

### 8. DefaultBrowsersIdentifier

In [26]:
train_dset_df.DefaultBrowsersIdentifier

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
567725   NaN
567726   NaN
567727   NaN
567728   NaN
567729   NaN
Name: DefaultBrowsersIdentifier, Length: 567730, dtype: float64

Hardly any non-null. DROP.

### 9. AVProductStatesIdentifier

In [27]:
train_dset_df.AVProductStatesIdentifier

0         53447.0
1         53447.0
2             NaN
3         53447.0
4         46669.0
           ...   
567725    53447.0
567726    22728.0
567727    53447.0
567728    53447.0
567729    53447.0
Name: AVProductStatesIdentifier, Length: 567730, dtype: float64

In [28]:
train_dset_df.AVProductStatesIdentifier.unique()

array([53447.,    nan, 46669., ..., 27464., 11168., 57845.])

Is categorical, and has missing values, and is not ordinal. But has waaay too many unique values to deal with. Maybe it can be binarized or something.

### 10. AVProductsInstalled

In [29]:
train_dset_df.AVProductsInstalled

0         1.0
1         1.0
2         NaN
3         1.0
4         2.0
         ... 
567725    1.0
567726    2.0
567727    1.0
567728    1.0
567729    1.0
Name: AVProductsInstalled, Length: 567730, dtype: float64

In [30]:
train_dset_df.AVProductsInstalled.unique()

array([ 1., nan,  2.,  3.,  4.,  5.,  6.])

Here, the number of NaNs is small. Further, it is ordinal data.

### 11. AVProductsEnabled

In [31]:
train_dset_df.AVProductsEnabled

0         1.0
1         1.0
2         NaN
3         1.0
4         1.0
         ... 
567725    1.0
567726    1.0
567727    1.0
567728    1.0
567729    1.0
Name: AVProductsEnabled, Length: 567730, dtype: float64

In [32]:
train_dset_df.AVProductsEnabled.unique()

array([ 1., nan,  2.,  0.,  3.,  4.,  5.])

Again, ordinal data which is already encoded. Missing values will have to be dealt with

### 12. HasTpm

In [33]:
train_dset_df.HasTpm

0         1
1         1
2         1
3         1
4         1
         ..
567725    1
567726    1
567727    1
567728    1
567729    1
Name: HasTpm, Length: 567730, dtype: int64

In [34]:
train_dset_df.HasTpm.unique()

array([1, 0])

Straightforward binary.

### 13. CountryIdentifier

In [35]:
train_dset_df.CountryIdentifier

0         201
1         147
2         220
3          53
4          41
         ... 
567725     29
567726     86
567727      9
567728    149
567729     66
Name: CountryIdentifier, Length: 567730, dtype: int64

In [36]:
train_dset_df.CountryIdentifier.nunique()

222

Again, it is categorical (nominal) but the number of categories would be large.

### 14. CityIdentifier

In [37]:
train_dset_df.CityIdentifier

0         101956.0
1          77794.0
2          40292.0
3         142425.0
4          22828.0
            ...   
567725      5444.0
567726     22702.0
567727    128857.0
567728      3167.0
567729    119877.0
Name: CityIdentifier, Length: 567730, dtype: float64

In [38]:
train_dset_df.CityIdentifier.nunique()

39730

It is not even worth considering. DROP or BINARIZE.

### 15. OrganizationIdentifier

In [39]:
train_dset_df.OrganizationIdentifier

0         27.0
1         27.0
2          NaN
3         27.0
4         18.0
          ... 
567725    18.0
567726    18.0
567727    27.0
567728    27.0
567729    27.0
Name: OrganizationIdentifier, Length: 567730, dtype: float64

In [40]:
train_dset_df.OrganizationIdentifier.nunique()

43

Lots of nulls. Better to drop.

### 16. GeoNameIdentifier

In [41]:
train_dset_df.GeoNameIdentifier

0         267.0
1         277.0
2         237.0
3          71.0
4          52.0
          ...  
567725     35.0
567726     64.0
567727    198.0
567728    181.0
567729     89.0
Name: GeoNameIdentifier, Length: 567730, dtype: float64

In [42]:
train_dset_df.GeoNameIdentifier.nunique()

271

DROP.

### 17. LocaleEnglishNameIdentifier

In [43]:
train_dset_df.LocaleEnglishNameIdentifier

0         251
1          75
2          72
3          52
4         217
         ... 
567725    171
567726     49
567727    229
567728     56
567729     88
Name: LocaleEnglishNameIdentifier, Length: 567730, dtype: int64

In [44]:
train_dset_df.LocaleEnglishNameIdentifier.nunique()

236

DROP.

### 18. Platform

In [45]:
train_dset_df.Platform

0         windows10
1         windows10
2         windows10
3         windows10
4         windows10
            ...    
567725    windows10
567726    windows10
567727    windows10
567728    windows10
567729    windows10
Name: Platform, Length: 567730, dtype: object

In [46]:
train_dset_df.Platform.unique()

array(['windows10', 'windows2016', 'windows8', 'windows7'], dtype=object)

This may be an important feature. I feel categorical-nominal

### 19. Processor

In [47]:
train_dset_df.Processor

0         x64
1         x64
2         x64
3         x64
4         x64
         ... 
567725    x64
567726    x64
567727    x64
567728    x64
567729    x64
Name: Processor, Length: 567730, dtype: object

In [48]:
train_dset_df.Processor.unique()

array(['x64', 'x86', 'arm64'], dtype=object)

Interesting. Will probably consider as categorical - nominal.

### 20. OsVer

In [49]:
train_dset_df.OsVer

0         10.0.0.0
1         10.0.0.0
2         10.0.0.0
3         10.0.0.0
4         10.0.0.0
            ...   
567725    10.0.0.0
567726    10.0.0.0
567727    10.0.0.0
567728    10.0.0.0
567729    10.0.0.0
Name: OsVer, Length: 567730, dtype: object

In [50]:
train_dset_df.OsVer.unique()

array(['10.0.0.0', '6.3.0.0', '6.1.1.0', '10.0.3.0', '10.0.1.0',
       '6.1.0.0', '10.0.0.112', '6.1.3.0', '10.0.7.0', '10.0.2.0',
       '10.0.16.0', '6.3.4.0', '10.0.5.18', '10.0.32.72', '10.0.153.153',
       '6.3.1.0'], dtype=object)

oNE-HOT

### 21. OsBuild

In [51]:
train_dset_df.OsBuild

0         16299
1         15063
2         16299
3         17134
4         10586
          ...  
567725    17134
567726    17134
567727    14393
567728    17134
567729    16299
Name: OsBuild, Length: 567730, dtype: int64

In [52]:
train_dset_df.OsBuild.nunique()

52

Maybe keep, maybe drop. If keep, it's categorical-nominal.

### 22. OsSuite

In [53]:
train_dset_df.OsSuite

0         256
1         256
2         768
3         256
4         768
         ... 
567725    256
567726    768
567727    768
567728    256
567729    256
Name: OsSuite, Length: 567730, dtype: int64

In [54]:
train_dset_df.OsSuite.unique()

array([256, 768, 272, 400, 305,  16, 784, 144, 274])

In [55]:
train_dset_df.OsSuite.nunique()

9

Keep -- categorical-nominal


### 23. OsPlatformSubRelease

In [56]:
train_dset_df.OsPlatformSubRelease

0         rs3
1         rs2
2         rs3
3         rs4
4         th2
         ... 
567725    rs4
567726    rs4
567727    rs1
567728    rs4
567729    rs3
Name: OsPlatformSubRelease, Length: 567730, dtype: object

In [57]:
train_dset_df.OsPlatformSubRelease.unique()

array(['rs3', 'rs2', 'rs4', 'th2', 'rs1', 'th1', 'prers5', 'windows8.1',
       'windows7'], dtype=object)

Keep. Categorical nominal

### 24. OsBuildLab

In [58]:
train_dset_df.OsBuildLab.nunique()

475

Drop, or binarize.

### 25. SkuEdition

In [59]:
train_dset_df.SkuEdition.unique()

array(['Pro', 'Home', 'Invalid', 'Enterprise', 'Education',
       'Enterprise LTSB', 'Server', 'Cloud'], dtype=object)

Categorical nominal. Keep.

### 26. IsProtected

In [60]:
train_dset_df.IsProtected

0         1.0
1         1.0
2         NaN
3         1.0
4         1.0
         ... 
567725    1.0
567726    1.0
567727    1.0
567728    1.0
567729    1.0
Name: IsProtected, Length: 567730, dtype: float64

In [61]:
train_dset_df.IsProtected.unique()

array([ 1., nan,  0.])

Some null values. Categorical-binary. Imputation needed. Probably will fill with zero.

### 27. AutoSampleOptIn

In [62]:
train_dset_df.AutoSampleOptIn

0         0
1         0
2         0
3         0
4         0
         ..
567725    0
567726    0
567727    0
567728    0
567729    0
Name: AutoSampleOptIn, Length: 567730, dtype: int64

In [63]:
train_dset_df.AutoSampleOptIn.unique()

array([0, 1])

Already encoded -- binary

### 28. PuaMode

There are 91 non-nulls. DROP.

### 29. SMode

In [64]:
train_dset_df.SMode

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ... 
567725    0.0
567726    0.0
567727    0.0
567728    0.0
567729    0.0
Name: SMode, Length: 567730, dtype: float64

In [65]:
train_dset_df.SMode.unique()

array([ 0., nan,  1.])

A few NaNs, which can probably safely be imputed to zero.

### 30. IeVerIdentifier

In [66]:
train_dset_df.IeVerIdentifier

0         117.0
1         108.0
2         111.0
3         137.0
4          76.0
          ...  
567725    137.0
567726    137.0
567727     98.0
567728    137.0
567729    111.0
Name: IeVerIdentifier, Length: 567730, dtype: float64

I think this means Internet Explorer version identifier. Probably safe to drop as it is again categorical nominal.

In [67]:
train_dset_df.IeVerIdentifier.nunique()

188

### 31. SmartScreen    

In [68]:
train_dset_df.SmartScreen

0                  NaN
1                  NaN
2         RequireAdmin
3                  NaN
4         RequireAdmin
              ...     
567725    RequireAdmin
567726    RequireAdmin
567727    RequireAdmin
567728             NaN
567729             NaN
Name: SmartScreen, Length: 567730, dtype: object

In [69]:
train_dset_df.SmartScreen.unique()

array([nan, 'RequireAdmin', 'ExistsNotSet', 'Off', 'Warn', 'Prompt',
       'Block', '&#x02;', '&#x01;', 'On', 'on', 'off', 'requireadmin',
       'prompt', 'Enabled'], dtype=object)

Aargh. There will have to be a  basic combination of features here. Probably a .lower will suffice. Further, there are a LOT of NaNs, at the same time this feature may have a lot of information. Probably best to fillnaa as off.

### 32. FireWall

In [70]:
train_dset_df.Firewall

0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
         ... 
567725    1.0
567726    1.0
567727    1.0
567728    1.0
567729    1.0
Name: Firewall, Length: 567730, dtype: float64

In [71]:
train_dset_df.Firewall.unique()

array([ 1.,  0., nan])

Binary.

A few null values. Probably safe to impute as zero

### 33. UacLuaenable

In [72]:
train_dset_df.UacLuaenable

0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
         ... 
567725    1.0
567726    1.0
567727    1.0
567728    1.0
567729    1.0
Name: UacLuaenable, Length: 567730, dtype: float64

In [73]:
train_dset_df.UacLuaenable.unique()

array([ 1.,  0., nan, 48., 49.,  2.])

Categorical- nominal with some null value imputation

### 34. Census_MDC2FormFactor

In [74]:
train_dset_df.Census_MDC2FormFactor

0            Notebook
1            Notebook
2            Notebook
3             Desktop
4            Notebook
             ...     
567725       Notebook
567726       Notebook
567727    Convertible
567728       Notebook
567729       Notebook
Name: Census_MDC2FormFactor, Length: 567730, dtype: object

In [75]:
train_dset_df.Census_MDC2FormFactor.unique()

array(['Notebook', 'Desktop', 'Detachable', 'Convertible', 'AllInOne',
       'SmallServer', 'PCOther', 'SmallTablet', 'LargeTablet',
       'MediumServer', 'LargeServer', 'ServerOther'], dtype=object)

Categorical - nominal

### 35. Census_DeviceFamily

In [76]:
train_dset_df.Census_DeviceFamily.unique()

array(['Windows.Desktop', 'Windows.Server', 'Windows'], dtype=object)

Categorical - nominal

### 36. Census_OEMNameIdentifier

In [77]:
train_dset_df.Census_OEMNameIdentifier.nunique()

1728

DROP.

### 37. Census_OEMModelIdentifier

In [78]:
train_dset_df.Census_OEMModelIdentifier.nunique()

44795

DROP.

### 38. Census_ProcessorCoreCount

In [79]:
train_dset_df.Census_ProcessorCoreCount.unique()

array([  2.,   4.,   8.,   6.,   1.,  12.,  16.,  nan,   5.,   3.,  24.,
        56.,  32.,  20.,  28.,  40.,  36.,  48.,   7.,  64.,  10.,  96.,
        52.,  44.,  14.,  18.,  72.,  26., 112.])

Keep as is? 

### 39. Census_ProcessorManufacturerIdentifier

In [80]:
train_dset_df.Census_ProcessorManufacturerIdentifier.unique()

array([ 5.,  1., nan,  3., 10.])

categorical - nominal

### 40. Census_ProcessorModelIdentifier

In [81]:
train_dset_df.Census_ProcessorModelIdentifier.nunique()

2334

DROP.

### 41. Census_ProcessorClass

In [82]:
train_dset_df.Census_ProcessorClass.isna().sum()

565597

DROP.

### 42. Census_PrimaryDiskTotalCapacity

In [83]:
train_dset_df.Census_PrimaryDiskTotalCapacity.nunique()

1323

This can probably be kept as it is in numerical form.

### 43. Census_PrimaryDiskTypeName

In [84]:
train_dset_df.Census_PrimaryDiskTypeName.unique()

array(['HDD', 'SSD', 'Unspecified', 'UNKNOWN', nan], dtype=object)

CUSTOM. Merge unspecified, unkown and nan.

### 44. Census_SystemVolumeTotalCapacity

In [85]:
train_dset_df.Census_SystemVolumeTotalCapacity.nunique()

151737

Again, can keep as numeric.

### 45. Census_HasOpticalDiskDrive

In [86]:
train_dset_df.Census_HasOpticalDiskDrive.unique()

array([0, 1])

Keep as  is. Binary encoding.

### 46. Census_TotalPhysicalRAM

In [87]:
train_dset_df.Census_TotalPhysicalRAM.nunique()

697

Keep as is.

### 47. Census_ChassisTypeName

In [88]:
train_dset_df.Census_ChassisTypeName.unique()

array(['Notebook', 'UNKNOWN', 'Desktop', 'Detachable', 'Laptop',
       'Portable', 'Convertible', 'AllinOne', 'Other', 'MiniTower',
       'Tower', 'HandHeld', 'Tablet', 'LowProfileDesktop', 'SpaceSaving',
       'BusExpansionChassis', 'MainServerChassis', 'LunchBox', nan,
       'MiniPC', 'Unknown', 'RackMountChassis', '0', 'PizzaBox',
       'SubNotebook', '35', 'StickPC', 'MultisystemChassis', '30', '49',
       '127', 'DockingStation', 'ExpansionChassis', 'SubChassis', '31'],
      dtype=object)

Categorical-nominal

### 48. Census_InternalPrimaryDiagonalDisplaySizeInInches

In [89]:
train_dset_df.Census_InternalPrimaryDiagonalDisplaySizeInInches.unique()

array([ 15.5,  14.1,  24. ,  11.4,  12.9,  10.1,  11.6,  13.9,  18.5,
        12.3,  19.5,  15. ,  23. ,  17. ,  21.3,  13.2,  27. ,  19.9,
         nan,  13.3,  15.6,  11.1,  14. ,  15.4,  15.3,  10.6,  22.2,
        10.4,  21.5,  20.7,  16.3,  16.8,  20. ,  48. ,   8.8,  15.9,
        17.1,  18.9,  40.2,  17.3,  17.2,   8. ,  18.4,  23.8,  22. ,
        16.2,  23.5,  12. ,   9.1,  18.1,  15.7,  19. ,  21.7,  61.2,
        10.3,  23.4,  21.6,  10. ,  19.4,  21. ,  11. ,  12.5,  24.1,
        46. ,  42.5,  17.7,  34.1,  16.7,  20.1,  27.7,  57.8,  20.4,
        10.8,  15.2,   6.7,  32. ,  24.5,  23.1,   6.9,  13.5,  72.3,
        19.2,  31.5,  14.9,  46.1,  29.4,  19.1,  11.5,  52. ,  17.6,
         7.9,   9. ,  12.2,  20.8,  26. ,  12.1,  28.6,  27.5,   9.9,
        49.7,  27.9,  26.4,  11.8,   8.9,  14.7,  42.3,  16.4,  23.2,
        17.5,  18.7,  28.7,   9.8,  40.1,  59.5,  50. ,  36.2,   8.5,
        21.8,  23.6,  20.6,  27.2,  14.6,  14.8,  26.6,  14.5,  16. ,
        21.9,   8.1,

Keep as is.

### 49. Census_Internal_Primary_Display_Resolution_Horizontal

In [90]:
train_dset_df.Census_InternalPrimaryDisplayResolutionHorizontal

0         1366.0
1         1280.0
2         1366.0
3         1440.0
4         1024.0
           ...  
567725    1366.0
567726    1920.0
567727    1366.0
567728    1280.0
567729    1366.0
Name: Census_InternalPrimaryDisplayResolutionHorizontal, Length: 567730, dtype: float64

CUSTOM. Take the product of the horizontal and vertical resolutions as one feature, and their ratios as another feature.

### 50. Census_InternalPrimaryDisplayResolutionVertical

As above.

### 51. Census_PowerPlatformRoleName

In [91]:
train_dset_df.Census_PowerPlatformRoleName.unique()

array(['Mobile', 'Desktop', 'Slate', 'SOHOServer', 'AppliancePC',
       'Workstation', 'UNKNOWN', 'EnterpriseServer', 'PerformanceServer',
       nan], dtype=object)

CUSTOM. Merge Nan and Unknown, and deal with the rest accordingly. Categorical nominal.

### 52. Census_InternalBatteryType

In [92]:
train_dset_df.Census_InternalBatteryType.unique()

array([nan, 'lion', 'nimh', '#', 'li-i', 'lip', 'li p', 'liio', 'unkn',
       'bq20', 'li', 'real', 'vbox', 'pbac', '4cel', 'lipp', 'batt',
       'lgi0', 'lhp0', 'ithi', 'lit', 'lipo', 'virt', 'pad0', 'lio',
       'ram', '2337', 'a132', 'ca48'], dtype=object)

Large number of NaNs. Drop? Probably. Further, noisy as hell.

### 53. Census_InternalBatteryNumberOfCharges

In [93]:
train_dset_df.Census_InternalBatteryNumberOfCharges.nunique()

6542

Can probably impute the remaining to zero.

### 54. Census_OSVersion

In [94]:
train_dset_df.Census_OSVersion.nunique()

310

DROP.

### 55. Census_OSArchitecture

In [95]:
train_dset_df.Census_OSArchitecture.unique()

array(['amd64', 'x86', 'arm64'], dtype=object)

This looks strangely familiar. Can drop.

### 56. Census_OSBranch

In [96]:
train_dset_df.Census_OSBranch.nunique()

21

Can probably drop

### 57. Census_OSBuildNumber

In [97]:
train_dset_df.Census_OSBuildNumber.nunique()

68

Can drop

### 58. Census_OSBuildRevision

In [98]:
train_dset_df.Census_OSBuildRevision.nunique()

242

Can drop

### 59. Census_OSEdition

In [99]:
train_dset_df.Census_OSEdition.nunique()

24

Itching as I may be to drop this, this could be pretty relevant. Better to keep.

### 60. Census_OSSkuName

In [100]:
train_dset_df.Census_OSSkuName.nunique()

20

Looks similar to the previous one. Can drop.

### 61. Census_OSInstallTypeName

In [101]:
train_dset_df.Census_OSInstallTypeName.unique()

array(['IBSClean', 'Upgrade', 'Reset', 'Other', 'UUPUpgrade', 'Update',
       'Refresh', 'Clean', 'CleanPCRefresh'], dtype=object)

Can keep. Is probably needed.

### 62. Census_OSInstallLanguageIdentifier

In [102]:
train_dset_df.Census_OSInstallLanguageIdentifier.unique()

array([35.,  8.,  4., 10., 39., 29., 14., 27.,  9.,  7., 37., 18., 21.,
        5., 28., 26., 25.,  1., 20., 24., 15., 17., 33.,  6., 23., 13.,
        3., 12., nan, 19., 30., 34., 11., 31., 38., 36., 32., 16.,  2.,
       22.])

Null value imputation needed, but can probably manage the number of columns just fine.

### 63. Census_OSUILocaleIdentifier

In [103]:
train_dset_df.Census_OSUILocaleIdentifier.unique()

array([148,  31,  24,  35, 160, 125,  49, 120,  34,  30, 158,  72,  90,
        26, 123, 119, 115,   5,  83, 109,  58,  64, 140,  28, 105,  48,
        20,  44,  74, 128, 145, 156, 130,  38, 126,  17,  68, 159, 151,
       136,  62,  73,  11,  92, 146,  39,  40,   6,  15,  54,  12,  42,
        32, 116, 122,  95,  36,  99,  59,  37,  25,   7,  86, 162, 110,
        21, 161, 157,  81,  70, 129,   9,  50,  91,  51, 121, 131,  82,
       152,  76,  84,  16, 132,  63,  60,  13, 124,  27, 139, 153,  29,
        19,  69,  93,  65])

Probably important... certain locales may be prone to virus events. Must keep. Categorical nominal.

### 64. Census_OSWUAutoUpdateOptionsName

In [104]:
train_dset_df.Census_OSWUAutoUpdateOptionsName.unique()

array(['UNKNOWN', 'FullAuto', 'Notify',
       'AutoInstallAndRebootAtMaintenanceTime', 'DownloadNotify', 'Off'],
      dtype=object)

Categorical-nominal. keep.

### 65. Census_IsPortableOperatingSystem

In [105]:
train_dset_df.Census_IsPortableOperatingSystem.unique()

array([0, 1])

Keep as is -- binary encoded.

### 66. Census_GenuineStateName

In [106]:
train_dset_df.Census_GenuineStateName.unique()

array(['IS_GENUINE', 'INVALID_LICENSE', 'OFFLINE', 'UNKNOWN'],
      dtype=object)

Categorical nominal. Probably an important feature.

### 67. Census_ActivationChannel

In [107]:
train_dset_df.Census_ActivationChannel.unique()

array(['Retail', 'OEM:DM', 'Volume:GVLK', 'OEM:NONSLP', 'Volume:MAK',
       'Retail:TB:Eval'], dtype=object)

Keep. Categorical nominal.

### 68. Census_IsFlightingInternal

In [108]:
train_dset_df.Census_IsFlightingInternal.unique()

array([nan,  0.,  1.])

A lot of null values. Drop.

### 69. Census_IsFlightsDisabled

In [109]:
train_dset_df.Census_IsFlightsDisabled.unique()

array([ 0., nan,  1.])

Impute the value to the majority class. Keep as is.

### 70. Census_FlightRing

In [110]:
train_dset_df.Census_FlightRing.unique()

array(['NOT_SET', 'Retail', 'Unknown', 'Disabled', 'WIS', 'WIF', 'RP',
       'OSG'], dtype=object)

No clue what this is. Categorical-nominal.

### 71. Census_ThresholdOptIn

In [111]:
train_dset_df.Census_ThresholdOptIn.unique()

array([nan,  0.,  1.])

Lots of null values. Drop.

### 73. Census_FirmwareManufacturerIdentifier

In [112]:
train_dset_df.Census_FirmwareManufacturerIdentifier.nunique()

334

A lot of columns to categorical encode. Probably worth dropping -- unless there are some firmwares which are highly prone to viruses?? Okay, drop.

### 74. Census_FirmwareVersionIdentifier

In [113]:
train_dset_df.Census_FirmwareVersionIdentifier.nunique()

25128

DROP without prejudice.

### 74. Census_IsSecureBootEnabled

In [114]:
train_dset_df.Census_IsSecureBootEnabled.unique()

array([0, 1])

Keep as-is.

### 75. Census_IsWIMBootEnabled

In [115]:
train_dset_df.Census_IsWIMBootEnabled.unique()

array([nan,  0.])

Lots of null values. DROP.

### 76. Census_IsVirtualDevice

In [116]:
train_dset_df.Census_IsVirtualDevice.unique()

array([ 0.,  1., nan])

Impute nan to zero. Rest keep as is.

### 77. Census_IsTouchEnabled

In [117]:
train_dset_df.Census_IsTouchEnabled.unique()

array([0, 1])

Keep as is.

### 78. Census_IsPenCapable

In [118]:
train_dset_df.Census_IsPenCapable.unique()

array([0, 1])

Keep as is.

### 80. Census_IsAlwaysOnAlwaysConnectedCapable

In [119]:
train_dset_df.Census_IsAlwaysOnAlwaysConnectedCapable.unique()

array([ 0.,  1., nan])

Impute to zero. Binary as-is.

### 80. Wdft_IsGamer

In [120]:
train_dset_df.Wdft_IsGamer.unique()

array([nan,  1.,  0.])

Impute nan to zero.

### 81. Wdft_RegionIdentifier

In [121]:
train_dset_df.Wdft_RegionIdentifier.unique()

array([nan, 11., 15., 10.,  7.,  3.,  1.,  5.,  6.,  4., 13., 12.,  8.,
        2.,  9., 14.])

Keep unless it looks familiar. Categorical-encode nominal.

### 82. HasDetections

In [122]:
train_dset_df.HasDetections.unique()

array([0, 1])

**TARGET**

### The table

In [123]:
columns_list = pd.read_csv("2020_11_17_categories.csv", delimiter=" ")

In [124]:
columns_list

feature_name  keep_as_is  label_encode  \
0                         MachineIdentifier           0             0   
1                               ProductName           0             0   
2                             EngineVersion           0             0   
3                                AppVersion           0             0   
4                              AvSigVersion           0             0   
..                                      ...         ...           ...   
78                      Census_IsPenCapable           1             0   
79  Census_IsAlwaysOnAlwaysConnectedCapable           1             0   
80                             Wdft_IsGamer           1             0   
81                    Wdft_RegionIdentifier           0             0   
82                            HasDetections           1             0   

    one_hot_encode  custom_encode  null_value_impute  drop  
0                0              0                  0     1  
1                1              0                  0     0  
2                1              0                  0     0  
3                0              0                  0     1  
4                0              0                  0     1  
..             ...            ...                ...   ...  
78               0              0                  0     0  
79               0              0                  1     0  
80               0              0                  1     0  
81               1              0                  1     0  
82               0              0                  0     0  

[83 rows x 7 columns]

In [125]:
    columns_names= list(train_dset_df.columns)

In [127]:
columns_df = columns_list

In [128]:
list(columns_df.columns)

['feature_name',
 'keep_as_is',
 'label_encode',
 'one_hot_encode',
 'custom_encode',
 'null_value_impute',
 'drop']

In [130]:
columns_df.set_index("feature_name", inplace=True)


In [134]:
for column in columns_names:
    if columns_df.loc[column, "drop"] == 0:
        if train_dset_df[column].isna().sum() > 0:
            print("NULLS in", column)
            columns_df.loc[column,"null_value_impute"] = 1

NULLS in RtpStateBitfield
NULLS in AVProductsInstalled
NULLS in AVProductsEnabled
NULLS in IsProtected
NULLS in SMode
NULLS in SmartScreen
NULLS in Firewall
NULLS in UacLuaenable
NULLS in Census_ProcessorCoreCount
NULLS in Census_ProcessorManufacturerIdentifier
NULLS in Census_PrimaryDiskTotalCapacity
NULLS in Census_PrimaryDiskTypeName
NULLS in Census_SystemVolumeTotalCapacity
NULLS in Census_TotalPhysicalRAM
NULLS in Census_ChassisTypeName
NULLS in Census_InternalPrimaryDisplayResolutionHorizontal
NULLS in Census_InternalPrimaryDisplayResolutionVertical
NULLS in Census_PowerPlatformRoleName
NULLS in Census_InternalBatteryNumberOfCharges
NULLS in Census_OSInstallLanguageIdentifier
NULLS in Census_IsFlightsDisabled
NULLS in Census_IsWIMBootEnabled
NULLS in Census_IsVirtualDevice
NULLS in Census_IsAlwaysOnAlwaysConnectedCapable
NULLS in Wdft_IsGamer
NULLS in Wdft_RegionIdentifier


In [136]:
columns_df.to_csv("2020_11_19_categories.csv")